"""Add a class to my database

Revision ID: 981a9bd29d0c
Revises: 9f0ac53ddbdc
Create Date: 2020-07-22 20:30:26.104715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981a9bd29d0c'
down_revision = '9f0ac53ddbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
